### ISSUE TITLE
Firing rate CJ cells

### ISSUE THREAD

**Issue by CynthiaRais** [CynthiaRais/Rustichini2015#2]
![capture d ecran 2017-05-01 a 18 55 43](https://cloud.githubusercontent.com/assets/27814843/25586877/a5b2b516-2ea1-11e7-9fe1-ed032ae161a1.png)
![capture d ecran 2017-05-01 a 18 56 51](https://cloud.githubusercontent.com/assets/27814843/25586882/ada69652-2ea1-11e7-86bf-b6c7fbc0a640.png)
When I test the code with one trial, I get very high firing rate of CJ quickly.
At t = 0.002s, the firing rate is already at ~16 spikes/s.
And at t= 0.0055s, the firing rate exceeds 166 spikes/s.
Looking at phi (equation 6), at t = 0.002s, I have phi ~ 57,55.
In the equation, the only variable is I_syn, so I look at it.
All the terms of I_syn are low compared to I_ampa_ext (equation 7).
But I_ampa_ext is determined by a constant term and the white noise, that is negligible. 

Would there be some errors in the code units?

**Comment by benureau** [comment]
I looked over the beginning of the code in details. There was a problem in [equation 2 and 5 ](https://github.com/CynthiaRais/Rustichini2015/blob/f85e11186ded5bbbd785d52941a49c5f4bebe032/code/Model.py#L110-L117), that [I corrected here](https://github.com/benureau/Rustichini2015/commit/7eb57f678186602829b049116e4af7c79ab9871f). I left it to you to see if that solves anything.

I also did a costemic overhaul, so that most variable names match the article. Everything is in the PR https://github.com/CynthiaRais/Rustichini2015/pull/3. To merge before doing changes.

**Comment by CynthiaRais** [comment]
The problem was due to a problem in the function cv_cells, that had been corrected [here](https://github.com/CynthiaRais/Rustichini2015/commit/ee9c1d9fa264827ac472f33768bd1ed059d48fef). But there is a still a firing rate too high for CJ cells.

**Comment by benureau** [comment]
Thanks. Could you describe precisely the problem of the too high firing rate (with possibly graphs from the article and from the code) in a new issue?
